# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order_nr', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_bill_firstname', models.CharField(max_length=250)),
                ('user_bill_lastname', models.CharField(max_length=250)),
                ('order_date', models.DateTimeField()),
                ('order_payment', models.CharField(max_length=250)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('voucher_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('voucher_nr', models.CharField(blank=True, max_length=250)),
                ('article_nr', models.CharField(blank=True, max_length=250)),
                ('article_title', models.CharField(max_length=250)),
                ('article_quantity', models.IntegerField()),
                ('article_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('country_title', models.CharField(max_length=250)),
                ('order_delivery_cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('user_address', models.CharField(max_length=250)),
                ('user_bill_street', models.CharField(max_length=250)),
                ('user_bill_street_nr', models.CharField(max_length=250)),
                ('user_bill_zipcode', models.CharField(max_length=250)),
                ('user_bill_city', models.CharField(max_length=250)),
                ('user_delivery_firstname', models.CharField(blank=True, max_length=250)),
                ('user_delivery_lastname', models.CharField(blank=True, max_length=250)),
                ('user_delivery_street', models.CharField(blank=True, max_length=250)),
                ('user_delivery_street_nr', models.CharField(blank=True, max_length=250)),
                ('user_delivery_zipcode', models.IntegerField(blank=True, max_length=250)),
                ('user_delivery_city', models.CharField(blank=True, max_length=250)),
                ('status', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
