# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20161202_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_delivery_zipcode',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
